//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Scripts/Player/MainController.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @MainController: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @MainController()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""MainController"",
    ""maps"": [
        {
            ""name"": ""Movement"",
            ""id"": ""b9dc704a-080d-4cfb-a5b6-5ce6638d3c36"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""PassThrough"",
                    ""id"": ""e3c10e2b-d77e-494d-9c8c-e88e8c6ae597"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Camera"",
                    ""type"": ""PassThrough"",
                    ""id"": ""734f520f-0483-432e-aaa3-718203c9b19c"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Run"",
                    ""type"": ""Button"",
                    ""id"": ""81b1e9e3-b7b6-4d64-86af-e1d740781caa"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Quick Turn"",
                    ""type"": ""Button"",
                    ""id"": ""291e914a-f277-48e2-983e-80aeb459ba21"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""4961ec59-e0a6-4fa7-acbb-5803ff6fc4fb"",
                    ""path"": ""2DVector(mode=2)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""f2568a83-8449-478c-9495-41d90171f874"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""3459187a-0f9e-489b-a54e-24298ff3c3c2"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""f7048677-10c9-480a-896f-bef02bccc9a8"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""ce39e09f-df4f-442a-b574-deca99e83a0d"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Gamepad"",
                    ""id"": ""0155d04d-4d77-43f6-898e-3ebf09ed75f4"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""cb907cff-089c-4894-9ccf-51201f1d68ef"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""30067690-2751-4bfe-b533-2c92927aab72"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""beb9e22b-288d-44d6-b824-a19c2ac22660"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""056b0817-664c-41f7-82ea-f845256f70bd"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""51f87ec7-d450-405e-b345-dfbed7caa945"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Camera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Gamepad"",
                    ""id"": ""7f9e5e47-5268-4c25-b1a7-2ef7e67015fe"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Camera"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""d3d714c8-b6cc-4740-b809-c68e71c40208"",
                    ""path"": ""<Gamepad>/rightStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Camera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""10e78cff-1ce8-4649-8d78-133eaff93761"",
                    ""path"": ""<Gamepad>/rightStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Camera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""0066ba6e-3146-4e7e-a1aa-bc83080f33a1"",
                    ""path"": ""<Gamepad>/rightStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Camera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""1676dc80-ae85-434d-b4be-6f11eb3ccb89"",
                    ""path"": ""<Gamepad>/rightStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Camera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""15403d98-7311-4ac6-9d37-18c03bfce564"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1f093e48-c597-48e9-a337-d76e3381438a"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e8594ca7-342e-46fa-ad98-d69a0bf2bbb1"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Quick Turn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""569b50b9-5d8f-4f3b-b37c-3b11be8d3839"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Quick Turn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Player_Actions"",
            ""id"": ""f4e909c0-7ef4-4ad6-a51c-3885c055e51e"",
            ""actions"": [
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""b05c4ed8-3985-4af8-b423-b8860d7eddb5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Sanity_HUD_Toggle"",
                    ""type"": ""Button"",
                    ""id"": ""852fdf3a-f818-43b7-916d-c86e90f5dc21"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UseItem"",
                    ""type"": ""Button"",
                    ""id"": ""c7d849f3-84a2-4c45-8465-d6e4b2e277f4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UseRightHand"",
                    ""type"": ""Button"",
                    ""id"": ""af762a79-70f1-4d6f-b8c5-0c7bbd3e8fea"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UseLeftHand"",
                    ""type"": ""Button"",
                    ""id"": ""48035c03-0a74-4c93-8b7c-54dc82aad427"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UseBeltSlot1"",
                    ""type"": ""Button"",
                    ""id"": ""d4f7b416-82c5-4fe6-9101-769a08582358"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UseBeltSlot2"",
                    ""type"": ""Button"",
                    ""id"": ""29456f74-0ccc-4f4b-a769-575f8e0f6b9f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UseBeltSlot3"",
                    ""type"": ""Button"",
                    ""id"": ""d7e3d38f-897c-4b51-8410-1b3117f2cbfc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NavigateSlots"",
                    ""type"": ""Value"",
                    ""id"": ""e91a6d90-1ed8-4888-8c3f-e4acd2401648"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""83a21065-4a74-4fcd-937d-f14af48e2323"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f9150989-fe7c-4124-b8b2-a63d074c6db2"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""06d4015d-2400-4425-a4c3-567d3ec10dfd"",
                    ""path"": ""<Gamepad>/leftStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sanity_HUD_Toggle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f8d3129c-ed45-4768-9bf3-0448e0d85962"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sanity_HUD_Toggle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3737e352-0f92-424c-9249-4610edb1e35d"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseItem"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3263d638-1419-4fa0-b715-ee61cbe73bbd"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseItem"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a6fa7678-5820-473f-82c2-c3fe98b5bfe0"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseRightHand"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a4996b5b-3f72-4e84-953e-6a93cbaa69ff"",
                    ""path"": ""<Keyboard>/g"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseLeftHand"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c0e94e9b-aee1-47e2-8580-c071dd829d1e"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseBeltSlot1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fc383c79-6fc7-4e7a-9a58-14ed3e3bfcb7"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseBeltSlot2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bce11851-acbb-40de-a73d-b50cce37f66d"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseBeltSlot3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""60a16de4-5459-4d33-86b6-eff471d3a968"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavigateSlots"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""a501370e-b1df-4599-8bfb-25a0be9ef885"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavigateSlots"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""9b6ccd59-f73e-4e9b-9733-c51ca891a430"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavigateSlots"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""7e1f5689-d09b-43db-be15-f38bff22b55d"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavigateSlots"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""2069e349-d6ab-4881-99c0-dbb74a4e115b"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavigateSlots"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Movement
        m_Movement = asset.FindActionMap("Movement", throwIfNotFound: true);
        m_Movement_Movement = m_Movement.FindAction("Movement", throwIfNotFound: true);
        m_Movement_Camera = m_Movement.FindAction("Camera", throwIfNotFound: true);
        m_Movement_Run = m_Movement.FindAction("Run", throwIfNotFound: true);
        m_Movement_QuickTurn = m_Movement.FindAction("Quick Turn", throwIfNotFound: true);
        // Player_Actions
        m_Player_Actions = asset.FindActionMap("Player_Actions", throwIfNotFound: true);
        m_Player_Actions_Interact = m_Player_Actions.FindAction("Interact", throwIfNotFound: true);
        m_Player_Actions_Sanity_HUD_Toggle = m_Player_Actions.FindAction("Sanity_HUD_Toggle", throwIfNotFound: true);
        m_Player_Actions_UseItem = m_Player_Actions.FindAction("UseItem", throwIfNotFound: true);
        m_Player_Actions_UseRightHand = m_Player_Actions.FindAction("UseRightHand", throwIfNotFound: true);
        m_Player_Actions_UseLeftHand = m_Player_Actions.FindAction("UseLeftHand", throwIfNotFound: true);
        m_Player_Actions_UseBeltSlot1 = m_Player_Actions.FindAction("UseBeltSlot1", throwIfNotFound: true);
        m_Player_Actions_UseBeltSlot2 = m_Player_Actions.FindAction("UseBeltSlot2", throwIfNotFound: true);
        m_Player_Actions_UseBeltSlot3 = m_Player_Actions.FindAction("UseBeltSlot3", throwIfNotFound: true);
        m_Player_Actions_NavigateSlots = m_Player_Actions.FindAction("NavigateSlots", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Movement
    private readonly InputActionMap m_Movement;
    private List<IMovementActions> m_MovementActionsCallbackInterfaces = new List<IMovementActions>();
    private readonly InputAction m_Movement_Movement;
    private readonly InputAction m_Movement_Camera;
    private readonly InputAction m_Movement_Run;
    private readonly InputAction m_Movement_QuickTurn;
    public struct MovementActions
    {
        private @MainController m_Wrapper;
        public MovementActions(@MainController wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_Movement_Movement;
        public InputAction @Camera => m_Wrapper.m_Movement_Camera;
        public InputAction @Run => m_Wrapper.m_Movement_Run;
        public InputAction @QuickTurn => m_Wrapper.m_Movement_QuickTurn;
        public InputActionMap Get() { return m_Wrapper.m_Movement; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MovementActions set) { return set.Get(); }
        public void AddCallbacks(IMovementActions instance)
        {
            if (instance == null || m_Wrapper.m_MovementActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_MovementActionsCallbackInterfaces.Add(instance);
            @Movement.started += instance.OnMovement;
            @Movement.performed += instance.OnMovement;
            @Movement.canceled += instance.OnMovement;
            @Camera.started += instance.OnCamera;
            @Camera.performed += instance.OnCamera;
            @Camera.canceled += instance.OnCamera;
            @Run.started += instance.OnRun;
            @Run.performed += instance.OnRun;
            @Run.canceled += instance.OnRun;
            @QuickTurn.started += instance.OnQuickTurn;
            @QuickTurn.performed += instance.OnQuickTurn;
            @QuickTurn.canceled += instance.OnQuickTurn;
        }

        private void UnregisterCallbacks(IMovementActions instance)
        {
            @Movement.started -= instance.OnMovement;
            @Movement.performed -= instance.OnMovement;
            @Movement.canceled -= instance.OnMovement;
            @Camera.started -= instance.OnCamera;
            @Camera.performed -= instance.OnCamera;
            @Camera.canceled -= instance.OnCamera;
            @Run.started -= instance.OnRun;
            @Run.performed -= instance.OnRun;
            @Run.canceled -= instance.OnRun;
            @QuickTurn.started -= instance.OnQuickTurn;
            @QuickTurn.performed -= instance.OnQuickTurn;
            @QuickTurn.canceled -= instance.OnQuickTurn;
        }

        public void RemoveCallbacks(IMovementActions instance)
        {
            if (m_Wrapper.m_MovementActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IMovementActions instance)
        {
            foreach (var item in m_Wrapper.m_MovementActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_MovementActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public MovementActions @Movement => new MovementActions(this);

    // Player_Actions
    private readonly InputActionMap m_Player_Actions;
    private List<IPlayer_ActionsActions> m_Player_ActionsActionsCallbackInterfaces = new List<IPlayer_ActionsActions>();
    private readonly InputAction m_Player_Actions_Interact;
    private readonly InputAction m_Player_Actions_Sanity_HUD_Toggle;
    private readonly InputAction m_Player_Actions_UseItem;
    private readonly InputAction m_Player_Actions_UseRightHand;
    private readonly InputAction m_Player_Actions_UseLeftHand;
    private readonly InputAction m_Player_Actions_UseBeltSlot1;
    private readonly InputAction m_Player_Actions_UseBeltSlot2;
    private readonly InputAction m_Player_Actions_UseBeltSlot3;
    private readonly InputAction m_Player_Actions_NavigateSlots;
    public struct Player_ActionsActions
    {
        private @MainController m_Wrapper;
        public Player_ActionsActions(@MainController wrapper) { m_Wrapper = wrapper; }
        public InputAction @Interact => m_Wrapper.m_Player_Actions_Interact;
        public InputAction @Sanity_HUD_Toggle => m_Wrapper.m_Player_Actions_Sanity_HUD_Toggle;
        public InputAction @UseItem => m_Wrapper.m_Player_Actions_UseItem;
        public InputAction @UseRightHand => m_Wrapper.m_Player_Actions_UseRightHand;
        public InputAction @UseLeftHand => m_Wrapper.m_Player_Actions_UseLeftHand;
        public InputAction @UseBeltSlot1 => m_Wrapper.m_Player_Actions_UseBeltSlot1;
        public InputAction @UseBeltSlot2 => m_Wrapper.m_Player_Actions_UseBeltSlot2;
        public InputAction @UseBeltSlot3 => m_Wrapper.m_Player_Actions_UseBeltSlot3;
        public InputAction @NavigateSlots => m_Wrapper.m_Player_Actions_NavigateSlots;
        public InputActionMap Get() { return m_Wrapper.m_Player_Actions; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(Player_ActionsActions set) { return set.Get(); }
        public void AddCallbacks(IPlayer_ActionsActions instance)
        {
            if (instance == null || m_Wrapper.m_Player_ActionsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_Player_ActionsActionsCallbackInterfaces.Add(instance);
            @Interact.started += instance.OnInteract;
            @Interact.performed += instance.OnInteract;
            @Interact.canceled += instance.OnInteract;
            @Sanity_HUD_Toggle.started += instance.OnSanity_HUD_Toggle;
            @Sanity_HUD_Toggle.performed += instance.OnSanity_HUD_Toggle;
            @Sanity_HUD_Toggle.canceled += instance.OnSanity_HUD_Toggle;
            @UseItem.started += instance.OnUseItem;
            @UseItem.performed += instance.OnUseItem;
            @UseItem.canceled += instance.OnUseItem;
            @UseRightHand.started += instance.OnUseRightHand;
            @UseRightHand.performed += instance.OnUseRightHand;
            @UseRightHand.canceled += instance.OnUseRightHand;
            @UseLeftHand.started += instance.OnUseLeftHand;
            @UseLeftHand.performed += instance.OnUseLeftHand;
            @UseLeftHand.canceled += instance.OnUseLeftHand;
            @UseBeltSlot1.started += instance.OnUseBeltSlot1;
            @UseBeltSlot1.performed += instance.OnUseBeltSlot1;
            @UseBeltSlot1.canceled += instance.OnUseBeltSlot1;
            @UseBeltSlot2.started += instance.OnUseBeltSlot2;
            @UseBeltSlot2.performed += instance.OnUseBeltSlot2;
            @UseBeltSlot2.canceled += instance.OnUseBeltSlot2;
            @UseBeltSlot3.started += instance.OnUseBeltSlot3;
            @UseBeltSlot3.performed += instance.OnUseBeltSlot3;
            @UseBeltSlot3.canceled += instance.OnUseBeltSlot3;
            @NavigateSlots.started += instance.OnNavigateSlots;
            @NavigateSlots.performed += instance.OnNavigateSlots;
            @NavigateSlots.canceled += instance.OnNavigateSlots;
        }

        private void UnregisterCallbacks(IPlayer_ActionsActions instance)
        {
            @Interact.started -= instance.OnInteract;
            @Interact.performed -= instance.OnInteract;
            @Interact.canceled -= instance.OnInteract;
            @Sanity_HUD_Toggle.started -= instance.OnSanity_HUD_Toggle;
            @Sanity_HUD_Toggle.performed -= instance.OnSanity_HUD_Toggle;
            @Sanity_HUD_Toggle.canceled -= instance.OnSanity_HUD_Toggle;
            @UseItem.started -= instance.OnUseItem;
            @UseItem.performed -= instance.OnUseItem;
            @UseItem.canceled -= instance.OnUseItem;
            @UseRightHand.started -= instance.OnUseRightHand;
            @UseRightHand.performed -= instance.OnUseRightHand;
            @UseRightHand.canceled -= instance.OnUseRightHand;
            @UseLeftHand.started -= instance.OnUseLeftHand;
            @UseLeftHand.performed -= instance.OnUseLeftHand;
            @UseLeftHand.canceled -= instance.OnUseLeftHand;
            @UseBeltSlot1.started -= instance.OnUseBeltSlot1;
            @UseBeltSlot1.performed -= instance.OnUseBeltSlot1;
            @UseBeltSlot1.canceled -= instance.OnUseBeltSlot1;
            @UseBeltSlot2.started -= instance.OnUseBeltSlot2;
            @UseBeltSlot2.performed -= instance.OnUseBeltSlot2;
            @UseBeltSlot2.canceled -= instance.OnUseBeltSlot2;
            @UseBeltSlot3.started -= instance.OnUseBeltSlot3;
            @UseBeltSlot3.performed -= instance.OnUseBeltSlot3;
            @UseBeltSlot3.canceled -= instance.OnUseBeltSlot3;
            @NavigateSlots.started -= instance.OnNavigateSlots;
            @NavigateSlots.performed -= instance.OnNavigateSlots;
            @NavigateSlots.canceled -= instance.OnNavigateSlots;
        }

        public void RemoveCallbacks(IPlayer_ActionsActions instance)
        {
            if (m_Wrapper.m_Player_ActionsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayer_ActionsActions instance)
        {
            foreach (var item in m_Wrapper.m_Player_ActionsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_Player_ActionsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public Player_ActionsActions @Player_Actions => new Player_ActionsActions(this);
    public interface IMovementActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnCamera(InputAction.CallbackContext context);
        void OnRun(InputAction.CallbackContext context);
        void OnQuickTurn(InputAction.CallbackContext context);
    }
    public interface IPlayer_ActionsActions
    {
        void OnInteract(InputAction.CallbackContext context);
        void OnSanity_HUD_Toggle(InputAction.CallbackContext context);
        void OnUseItem(InputAction.CallbackContext context);
        void OnUseRightHand(InputAction.CallbackContext context);
        void OnUseLeftHand(InputAction.CallbackContext context);
        void OnUseBeltSlot1(InputAction.CallbackContext context);
        void OnUseBeltSlot2(InputAction.CallbackContext context);
        void OnUseBeltSlot3(InputAction.CallbackContext context);
        void OnNavigateSlots(InputAction.CallbackContext context);
    }
}
